spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?userUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    root: warn
    com.wzz: info
  file: logs/blog-pro.log
server:
  port: 8081
