spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?userUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
logging:
  level:
    root: info
    com.wzz: debug
  file: logs/blog-dev.log